services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - .:/var/www/html
    env_file: .env
